/** @type {import('tailwindcss').Config} */
module.exports = {
   content: ['./src/**/*.{js,jsx,ts,tsx}'],
   theme: {
      extend: {
         screens: {
            tablet: '768px',
            laptop: '1024px',
            desktop: '1134px',
         },
         fontSize: {
            xs: '12px',
            sm: '14px',
            base: '16px',
            lg: '18px',
            xl: '20px',
            '2xl': '24px',
            '3xl': '30px',
         },
         colors: {
            black: 'var(--black)',
            white: 'vart(--white)',
            primary: 'var(--text-primary)',
            search: 'var(--text-search)',
            placeholder: 'var(--text-placeholder)',
            navigation: 'var(--text-navigation)',
            hover: 'var(--text-hover)',
            secondary: 'var(--text-secondary)',
            'purple-primary': 'var(--purple-primary)',
         },
         backgroundColor: {
            white: 'var(--white)',
            header: 'rgba(55, 7, 93, 0.8)',
            primary: 'var(--bg-primary)',
            layout: 'var(--bg-layout)',
            thumb: 'var(--thumb-color)',
            secondary: 'var(--bg-secondary)',
            alpha: 'var(--bg-alpha)',
            line: 'var(--line)',
            sidebar: 'var(--bg-sidebar)',
            loading: 'var(--bg-loading)',
            tooltip: 'var(--bg-tooltip)',
            controls: 'var(--bg-controls)',
            player: 'var(--bg-player-controls)',
            queue: 'var(--bg-player-queue)',
            'sidebar-popup': 'var(--bg-sidebar-popup)',
            'tag-active': 'var(--tag-active)',
            'progressbar-active': 'var(--bg-progressbar-active)',
            'progressbar-player': 'var(--bg-progressbar-player)',
            'dark-10': 'var(--dark-10)',
            'dark-50': 'var(--dark-50)',
            'dark-70': 'var(--dark-70)',
            'dark-80': 'var(--dark-80)',
            'purple-primary': 'var(--purple-primary)',
         },
         backgroundImage: {
            primary: 'var(--bg-primary)',
            logo: 'var(--logo)',
            'logo-small': 'var(--logo-small)',
            linear: 'var(--linear-gradient)',
            'player-img': 'var(--bg-player-img)',
         },
         backgroundSize: {
            full: '100%',
         },
         borderColor: {
            primary: 'var(--line)',
            'purple-primary': 'var(--purple-primary)',
            secondary: 'var(--border-secondary)',
            checkbox: 'var(--border-checkbox)',
         },
         maxHeight: {
            search: 'calc(100vh - 180px)',
         },
         height: {
            header: 'var(--header-height)',
            main: 'calc(100% - var(--player-height))',
            player: 'var(--player-height)',
            sidebar: 'calc(100vh - var(--player-height))',
         },
         width: {
            sidebar: 'var(--sidebar-width)',
            'sidebar-small': 'var(--sidebar-width-small)',
            header: 'calc(100% - var(--sidebar-width))',
            'header-small': 'calc(100% - var(--sidebar-width-small))',
            main: 'calc(100% - var(--sidebar-width))',
            'main-small': 'calc(100% - var(--sidebar-width-small))',
         },
         padding: {
            section: '0 var(--section-padding)',
            10: '10px',
         },
         margin: {
            section: 'var(--header-height)',
            10: '10px',
         },
         boxShadow: {
            image: '0 5px 8px 0 #00000033',
            btn: 'box-shadow: 0 1px 3px 0 #00000012',
            suggest: '0 4px 6px 0 #20212447;',
            menu: '0 0 5px 0 #00000033',
            header: '0 3px 5px var(--header-shadow)',
            skeleton: ' 0 0 50px 50px rgba(255, 255, 255, 0.3)',
            queue: '0 1px 0 rgba(0,0,0,0.3),0 1px 6px rgba(0,0,0,0.3),inset 0 1px 1px rgba(25,255,255,0.05)',
            'btn-arrow': '0 2px 4px 0 #e2666626',
         },
         zIndex: {
            1: '1',
            100: '100',
         },
         lineHeight: {
            normal: 'normal',
         },
      },
   },
   plugins: [],
};
